package it.unipi.riskDeV.model;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;
import org.springframework.data.mongodb.core.mapping.Field;

import it.unipi.riskDeV.DTO.PackageVersionDTO;

import java.util.ArrayList;
import java.util.List;

@Data
@AllArgsConstructor
@NoArgsConstructor
@Document(collection = "package")
public class PackageVersion {

    @Id
    private String id; // id is automatically generated by mongoDB

    @Field("package_name")
    private String packageName;

    private String version;

    @Field("version_array")  // it's only used to sort versions during queries
    private List<Integer> versionArray = new ArrayList<>();

    private String author;

    @Field("author_email")
    private String authorEmail;

    private String description;

    @Field("package_url")
    private String packageURL;

    @Field("documentation")
    private String documentationURL;

    @Field("upload_time")
    private String uploadTime;

    @Field("requires_dist")
    private List<Constraints> dependencies = new ArrayList<>();

    @Field("requires_python")
    private String requiresPython;
    
    @Field("risk_score")
    private Double riskScore;

    private List<EmbeddedVulnerability> vulnerabilities = new ArrayList<>();

    // Personalized getters to avoid null problems with lists
    // If mongo gives requires_dist == null, we have an empty list
    public List<Constraints> getDependencies() {
        if (dependencies == null) {
            return new ArrayList<>();
        }
        return dependencies;
    }

    // If mongo gives vulnerabilities == null, we have an empty list
    public List<EmbeddedVulnerability> getVulnerabilities() {
        if (vulnerabilities == null) {
            return new ArrayList<>();
        }
        return vulnerabilities;
    }
    
    // If versionArray is corrupted (==null) we use an empty array (to avoid crash)
    public List<Integer> getVersionArray() {
        if (versionArray == null) {
            return new ArrayList<>();
        }
        return versionArray;
    }

    @Data
    public static class EmbeddedVulnerability {

        @Field("cve_id")
        private String cveId;

        private String details;

        @Field("fixed_in")
        private List<String> fixedIn;
        
        private String link;
    }

    @Data
    public static class Constraints {

        private String name;

        private String version_gte;
        private String version_lte;
        private String version_gt;
        private String version_lt;
        private String version_eq;
        private String version_neq;
    }

    public PackageVersion(PackageVersionDTO dto) {
        this.packageName = dto.getPackageName();
        this.version = dto.getVersion();
        this.author = dto.getAuthor();
        this.authorEmail = dto.getAuthorEmail();
        this.description = dto.getDescription();
        this.packageURL = dto.getPackageURL();
        this.documentationURL = dto.getDocumentationURL();
        this.uploadTime = dto.getUploadTime();
        this.requiresPython = dto.getRequiresPython();
        this.riskScore = dto.getRiskScore();
        this.dependencies = dto.getDependencies() != null ? new ArrayList<>(dto.getDependencies()) : new ArrayList<>();
        this.vulnerabilities = dto.getVulnerabilities() != null ? dto.getVulnerabilities() : new ArrayList<>();
        this.versionArray = new ArrayList<>();
    }
}