package it.unipi.riskDeV.model;

import lombok.Data;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;
import org.springframework.data.mongodb.core.mapping.Field;

import java.util.ArrayList;
import java.util.List;

@Data
@Document(collection = "package")
public class PackageVersion {

    @Id
    private String id; // id is automatically generated by mongoDB

    @Field("package_name")
    private String packageName;

    private String version;

    @Field("version_array")  // it's only used to sort versions during queries
    private List<Integer> versionArray = new ArrayList<>();

    private String author;

    @Field("author_email")
    private String authorEmail;

    private String description;

    @Field("package_url")
    private String packageURL;

    @Field("documentation")
    private String documentationURL;

    @Field("upload_time")
    private String uploadTime;

    @Field("requires_dist")
    private List<String> dependencies = new ArrayList<>();

    @Field("requires_python")
    private String requiresPython;
    
    @Field("risk_score")
    private Double riskScore;

    private List<EmbeddedVulnerability> vulnerabilities = new ArrayList<>();

    // Personalized getters to avoid null problems with lists
    // If mongo gives requires_dist == null, we have an empty list
    public List<String> getDependencies() {
        if (dependencies == null) {
            return new ArrayList<>();
        }
        return dependencies;
    }

    // If mongo gives vulnerabilities == null, we have an empty list
    public List<EmbeddedVulnerability> getVulnerabilities() {
        if (vulnerabilities == null) {
            return new ArrayList<>();
        }
        return vulnerabilities;
    }
    
    // If versionArray is corrupted (==null) we use an empty array (to avoid crash)
    public List<Integer> getVersionArray() {
        if (versionArray == null) {
            return new ArrayList<>();
        }
        return versionArray;
    }

    @Data
    public static class EmbeddedVulnerability {

        @Field("cve_id")
        private String cveId;

        private String details;

        @Field("fixed_in")
        private List<String> fixedIn;
        
        private String link;
    }
}