package it.unipi.riskDeV.model;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;
import org.springframework.data.mongodb.core.mapping.Field;

import it.unipi.riskDeV.DTO.packageVersion.AddPackageVersionDTO;
import it.unipi.riskDeV.DTO.packageVersion.EmbeddedVulnerabilityDTO;
import it.unipi.riskDeV.DTO.packageVersion.PackageVersionDTO;
import it.unipi.riskDeV.util.DependencyParser;
import it.unipi.riskDeV.util.Helper;
import it.unipi.riskDeV.util.Utility;

import java.time.Instant;
import java.util.ArrayList;
import java.util.List;

@Data
@AllArgsConstructor
@NoArgsConstructor
@Document(collection = "package")
public class PackageVersion {

    @Id
    private String id; // id is automatically generated by mongoDB

    @Field("package_name")
    private String packageName;

    private String version;

    @Field("version_array")  // it's only used to sort versions during queries
    private List<Integer> versionArray = new ArrayList<>();

    private String author;

    @Field("author_email")
    private String authorEmail;

    private String description;

    @Field("package_url")
    private String packageURL;

    @Field("documentation")
    private String documentationURL;

    @Field("upload_time")
    private String uploadTime;

    @Field("requires_dist")
    private List<Constraints> dependencies = new ArrayList<>();

    @Field("requires_python")
    private String requiresPython;
    
    @Field("risk_score")
    private Double riskScore;

    private List<EmbeddedVulnerability> vulnerabilities = new ArrayList<>();    

    public PackageVersion(PackageVersionDTO dto) {
        this.packageName = dto.getPackageName();
        this.version = dto.getVersion();
        this.author = dto.getAuthor();
        this.authorEmail = dto.getAuthorEmail();
        this.description = dto.getDescription();
        this.packageURL = dto.getPackageURL();
        this.documentationURL = dto.getDocumentationURL();
        this.uploadTime = dto.getUploadTime();
        this.requiresPython = dto.getRequiresPython();
        this.riskScore = dto.getRiskScore();
        this.versionArray = new ArrayList<>();

        this.dependencies = new ArrayList<>();
        if (dto.getDependencies() != null) {
            for (String dep : dto.getDependencies()) {
                this.dependencies.add(DependencyParser.parseFullString(dep));
            }
        }

        this.vulnerabilities = new ArrayList<>();
        for(EmbeddedVulnerabilityDTO tmp: dto.getVulnerabilities()) {
            this.vulnerabilities.add(new EmbeddedVulnerability(tmp));
        }
    }

    public PackageVersion(AddPackageVersionDTO dto, Helper helper, Utility util) {
        this.packageName = dto.getPackageName();
        this.version = dto.getVersion();
        this.author = dto.getAuthor();
        this.authorEmail = dto.getAuthorEmail();
        this.description = dto.getDescription();
        this.packageURL = dto.getPackageURL();
        this.documentationURL = dto.getDocumentationURL();
        this.uploadTime = Instant.now().toString();
        this.requiresPython = dto.getRequiresPython();
        this.versionArray = util.generateVersionArray(dto.getVersion());
        
        this.dependencies = new ArrayList<>();
        if (dto.getDependencies() != null) {
            for (String dep : dto.getDependencies()) {
                this.dependencies.add(DependencyParser.parseFullString(dep));
            }
        }
        
        List<String> cveIds = new ArrayList<>();
        for (var vuln : this.vulnerabilities) {
            if (vuln.getCveId() != null) {
                cveIds.add(vuln.getCveId());
            }
        }

        this.riskScore = helper.getMaxBaseScore(cveIds);
    }
}